project:
  build: .
  volumes:
    - /var/jenkins_home/workspace/TestSpoon:/opt/workspace
    - /var/run/docker.sock:/var/run/docker.sock
    - ./dot-gradle:/root/.gradle
    - /dev/bus/usb:/dev/bus/usg
  command: "su -c 'touch dupa'"
  privileged: true
