project:
  build: .
  volumes:
    - .:/opt/workspace
    - /var/run/docker.sock:/var/run/docker.sock
    - ./dot-gradle:/root/.gradle
    - /dev/bus/usb:/dev/bus/usg
  command: "ls >> some.txt"
  privileged: true
