project:
  build: .
  volumes:
    - /home/admin/TestSpoonWithDocker/jenkins/jenkins-data/workspace/TestSpoon\ task:/opt/workspace
    - /var/run/docker.sock:/var/run/docker.sock
    - ./dot-gradle:/root/.gradle
    - /dev/bus/usb:/dev/bus/usg
  command: "./gradlew $TASKS"
  privileged: true
